# Generated by Django 3.2.9 on 2022-11-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='now_movie',
            name='backdrop_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
