# Generated by Django 3.2.9 on 2022-11-18 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.now_movie'),
        ),
    ]
