# Generated by Django 3.2.9 on 2022-11-24 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20221124_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='like_users',
        ),
    ]
