# Generated by Django 3.2.9 on 2022-11-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_comments_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='like_users',
        ),
    ]
